site_name: Go Package Notes
site_url: https://note.jinvic.top/gopkg-notes
repo_url: https://github.com/Jinvic/gopkg-notes
repo_name: Jinvic/gopkg-notes
site_description: some notes about go packages
site_author: Jinvic

theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    # - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share

nav:
  - Home: 'README.md'
  - Others: 'others.md'
  - Notes:
    - gorilla:
      - websocket: 'notes/gorilla-websocket.md'
      - ssessions: 'notes/gorilla-sessions.md'
    - samber:
      - lo: 'notes/samber-lo.md'
      - do: 'notes/samber-do.md'
    - viper: 'notes/viper.md'
    - zap: 'notes/zap.md'
    - jwt: 'notes/jwt.md'
    - uuid: 'notes/google-uuid.md'
    - zip: 'notes/archive-zip.md'
    - cast: 'notes/cast.md'
    - validator: 'notes/validator.md'

plugins:
  - search:
      lang:
        - zh
        - en
        