site_name: Go Package Notes
site_url: https://note.jinvic.top/gopkg-notes
repo_url: https://github.com/Jinvic/gopkg-notes
repo_name: Jinvic/gopkg-notes
site_description: some notes about go packages
site_author: Jinvic

theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    # - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share

nav:
  - Home: 'README.md'
  - Others: 'others.md'
  - Notes:
    - Standard:
      - archive:
        - zip: 'notes/standard/archive/zip.md'
    - ThridParty:
      - gorilla:
        - websocket: 'notes/thirdparty/gorilla/websocket.md'
        - ssessions: 'notes/thirdparty/gorilla/sessions.md'
      - samber:
        - lo: 'notes/thirdparty/samber/lo.md'
        - do: 'notes/thirdparty/samber/do.md'
      - spf13:
        - viper: 'notes/thirdparty/spf13/viper.md'
        - cast: 'notes/thirdparty/spf13/cast.md'
    - Others:
      - zap: 'notes/others/zap.md'
      - jwt: 'notes/others/jwt.md'
      - uuid: 'notes/others/uuid.md'
      - validator: 'notes/others/validator.md'
      - swag: 'notes/others/swag.md'

plugins:
  - search:
      lang:
        - zh
        - en
        